[package]
name = "foo"
version = "0.1.0"
authors = ["cowlicks"]
edition = "2018"

[lib]
name = "foo"
crate-type = ["lib", "staticlib"]


[dependencies]
tokio-tungstenite = "*"
tokio = { version = "1.5.0", features = ["full"] }
